### ISSUE TITLE
Post Json format

### ISSUE THREAD

**Issue by bobhsr** [tcdent/php-restclient#11]
There is POST method that has not been working.

This is sample CURL example at the service.

```json
{"email": "sam@email.com", "items": [{ "name": "api Name", "quantity": 10, "unit_price": 2}, { "name": "api 2", "quantity": "4", "unit_price": 3 }] 

}
```

Have the tried the following.

```php
$data = array(
        'email' => 'john@dow.com', 
        );
$data['items'] = array(
        'name' => 'fruits', 'quantity' => 4,
         'unit_price' => 7,
        );

$data2 = array(
            'email' => 'john@dow.com', 'currency' => 'USD',
            'country' => 'US', 'billing_first_name' => 'John',
            // 'items' => '',
            'items' =>  array(
            0 => array(
                'unit_price' => 10.00, 
                'name' => 'item1',
                'quantity' => 15
                ),
            1 => array(
                'unit_price' => 34.00, 
                'name' => 'item2', 
                'quantity' => 42
                )
            )

            );

$result = $api->post('invoice/', $data,
            array('Content-Type' => 'application/json'));
```

The service just accepts email, and ignores items.

**Comment by tcdent** [comment]
I believe you just need to call `json_encode` on your `$data` array.

Your execution could look like this (untested):

```
$result = $api->post('invoice/', json_encode($data), array('Content-Type' => 'application/json'));
```

**Comment by bobhsr** [comment]
with json_encode($data), the email does not get sent to service,

**Comment by tcdent** [comment]
Can you post the actual code you're executing, and the result you're getting?

To verify success `$result->info->http_code` is a good place to start. The README has more information on the response information available. 

Also `var_dump($result->response)` will give you the full text of the response, which will likely include an indicator of what went wrong if you are getting an HTTP code other than 200.

**Comment by bobhsr** [comment]
I am expanding POST request from the example at
https://github.com/tcdent/php-restclient/blob/master/test.php

JSON object needs to be in the folling format
{"email": "sam@email.com", "items": [{ "name": "api Name", "quantity": 10, "unit_price": 2}, { "name": "api 2", "quantity": "4", "unit_price": 3 }] 

}

when tried with this code based on example, the service just accepts email, and ignores items.

$data2 = array(
            'email' => 'john@dow.com',
            // 'items' => '',
            'items' =>  array(
            0 => array(
                'unit_price' => 10.00, 
                'name' => 'item1',
                'quantity' => 15
                ),
            1 => array(
                'unit_price' => 34.00, 
                'name' => 'item2', 
                'quantity' => 42
                )
            )

            );

$result = $api->post('invoice/', $data2,
            array('Content-Type' => 'application/json'));


$result->info->http_code 
shows 201 most the time, but it does not add items,

**Comment by tcdent** [comment]
I don't see where you're specifying a domain name, or instantiating the `RestClient` instance. 

    when tried with this code based on example, the service just accepts email, and ignores items.

Any error handling, messaging or response data is the responsibility of the API you are using. Can you try outputting the entire response body with `var_dump($result->response)`?

**Comment by tcdent** [comment]
Here is a basic example based on the information I have:

```php
$api = new RestClient(array(
    // replace with your actual API endpoint
    'base_url' => "https://api.domain-name.com"
));

// data pre-encoded as a JSON string
$data_string = '{"email": "sam@email.com", "items": [{ "name": "api Name", "quantity": 10, "unit_price": 2}, { "name": "api 2", "quantity": "4", "unit_price": 3 }]}';

// POST our JSON data to https://api.domain-name.com/invoice/
$result = $api->post('invoice/', $data_string, 
    array('Content-Type' => 'application/json'));

// look at the result
var_dump($result->info->http_code);
var_dump($result->response);
```

**Comment by bobhsr** [comment]
with '$data_string' the email is not getting sent either, is a required. now the service has error email is required

**Comment by tcdent** [comment]
Congratulations! We've verified you are connecting to the endpoint, so it's all about matching the exact request they expect in their documentation now. 

I don't have much information about what you're actually trying to do yet, but you're well on your way to accomplishing it, so it's hard to make accurate suggestions, but here are a few pointers:

Verify that the endpoint actually wants you to POST json data. 

Verify that your root JSON structure is correct. Is email supposed to be in the root node, or is there a wrapper?

If you have a link to public documentation I would be happy to review it.

**Comment by bobhsr** [comment]
This is what I have so far. 
I am trying to make a POST request to CoinsBill.
https://www.coinsbill.com/developers

```php
$api = new RestClient;
$api->set_option('base_url', 'https://www.coinsbill.com/api/');
$api->set_option('headers', array('Authorization' => 'Bearer a9esthaVUjOuvzTCSTXsJUCK0lCMCk'));
```

The above authorization always did not work, while adding to code did work

```php
curl_setopt($client->handle, CURLOPT_HTTPHEADER, array('authorization: Bearer a9esthaVUjOuvzTCSTXsJUCK0lCMCk));
```
The POST Request is based on tests,php. You did mention refer to README, but it does not have any POST example.

```php
$data = array(
            'email' => 'john@dow.com'
, 'currency' => 'USD',
            'country' => 'US', 'billing_first_name' => 'John',
            'items' =>  array(
            0 => array(
                'unit_price' => 10.00, 
                'name' => 'item1',
                'quantity' => 15
                ),
            1 => array(
                'unit_price' => 34.00, 
                'name' => 'item2', 
                'quantity' => 42
                )
            )

            );


// This service is able to accept other data than 'items'
$result = $api->post('invoice/', $data,
            array('Content-Type' => 'application/json'));

// Service does recieve any data
$result = $api->post('invoice/',  json_encode($data),,
            array('Content-Type' => 'application/json'));


// $data_string, service does not receieve any data
```

**Comment by tcdent** [comment]
Just tested this by modifying the example I included above, and works for me:

```php
$api = new RestClient(array(
    'base_url' => "https://www.coinsbill.com/api/", 
    'headers' => array(
        'Authorization' => "Bearer a9esthaVUjOuvzTCSTXsJUCK0lCMCk"
    )
));

$data_string = '{"email": "test@test.com", "items": [], "currency":"USD"}';

$result = $api->post('invoice/', $data_string, 
    array('Content-Type' => 'application/json'));

var_dump($result->info);
var_dump($result->response);
```

```
"{"orderId":"J8UDA","billing_first_name":"","billing_last_name":"","billing_address":"","billing_zip_code":"","billing_city":"","email":"test@test.com","country":"","currency":"USD","total":0.09,"status":"New Invoice ","invoice_url":"http://www.coinsbill.com/invoice/a/J8UDA","items":[],"tax":0.0,"subtotal":0.0,"paid":"0.0000000000","balance_remaining":0.09,"is_paid":false,"fees":0.09,"url":"http://www.coinsbill.com/api/invoice/J8UDA/","transactions":null,"recurrence_period":null,"recurrence_unit":null}"
```

To test the sanity, If I omit the 'currency' field, I get a JSON error in `$result->response` as expected:

```"{"currency":["This field is required."]}"```

Any data handling, errors or unexpected functionality are the responsibility of the API endpoint (coinsbill); you should open a support ticket with them if you are still in need of a solution.

**Comment by bobhsr** [comment]
The currency required error only comes back when we use a string,

```php
$data_string =
```
Replacing it with the entry is added, but not the items
```php
$data = array(
            'email' => 'john@dow.com', 'currency' => 'USD',
            'country' => 'US', 'billing_first_name' => 'John',
            'items' =>  array(
            0 => array(
                'unit_price' => 10.00, 
                'name' => 'item1',
                'quantity' => 15
                ),
            1 => array(
                'unit_price' => 34.00, 
                'name' => 'item2', 
                'quantity' => 42
                )
            )

            );


$result = $api->post('invoice/', $data,
            array('Content-Type' => 'application/json'));

```

With this service is able to accept most of other data, email, currency.
But it items do not work though

**Comment by bobhsr** [comment]
The Issue is the Items that I am trouble sending to the service.
