### ISSUE TITLE
can this library upload file?

### ISSUE THREAD

**Issue by navid-dada** [tcdent/php-restclient#13]
can i upload file using this library on remote server???

**Comment by tcdent** [comment]
This depends heavily on what your remote server is expecting uploaded file data to look like, but if you are emulating an HTML form, it would work like this (untested):

```
$api = new RestClient();
$result = $api->post("/", [
    'file_data' => "@/tmp/filename.jpg"
]);
```

`file_data` is the name of the form parameter your server is expecting. You'll need to have read access to the file path referenced.

Source: https://curl.haxx.se/libcurl/php/examples/httpfileupload.html
