### ISSUE TITLE
"format" gets always appended to the URL

### ISSUE THREAD

**Issue by yedey** [tcdent/php-restclient#15]
Hi,

If you set format eg. to "json", the execute function always appends it as file extension to the url because of this:
`        if($client->options['format'])
            $client->url .= '.'.$client->options['format'];`

There should be an option to disable that. In my case, the service doesn't accept any file extension. If I leave format empty I get "Response format could not be determined.", which indicates that get_response_format couldn't auto detect the response format. Even if it would auto detect, I wouldn't want to rely on that, because the service response headers might change although the response content is still the same.

Just a boolean option and a check in the if statement above should fix that.

**Comment by tcdent** [comment]
If you are making explicit requests for content with a 'json', etc. extension then it is a very good indicator that the endpoint will be returning that content-type, regardless of headers. This is widely used on API's like Twitter and Vimeo. 

In the case that not format is specified, we *only* have the response `Content-Type` headers available to identify the response format; this is the default behavior. 

If your endpoint is not responding with the correct headers, it's broken, and prevents us from making any assumptions. 

You can either decode the response explicitly yourself:

``` php
$result = $api->get("/");
json_decode($result->response);
```

or, as a hack (to deal with the upstream hack) defining a decoder for the response content type. This will allow you to still utilize automatic decoding and iterable/array access. 

``` php 
$api->register_decoder('text', function($data){ return json_decode($data); });
$result = $api->get("/");
var_dump($result->decode_response());
```

**Comment by yedey** [comment]
You don't get the point I tried to make. The repsonse content-type of the api might change as it is not specified, but I know exactly that the content will always be json (that is specified). I'm not talking about public APIs here. When I get a spec for a REST Api that doesn't mention the response content-type header explicitly as constant, I cannot rely on a decoder that is applied using this "looks right for now" guess work.
