### ISSUE TITLE
Repeat parameter key

### ISSUE THREAD

**Issue by basvandertogt** [tcdent/php-restclient#26]
Is it possible to post a repeatable parameter key like this?

`
{
    "repeatableKey" : {
        "bla":"bla",
        "bla":"bla",
    },
    "repeatableKey" : {
        "bla":"bla",
        "bla":"bla",
    },
    "repeatableKey" : {
        "bla":"bla",
        "bla":"bla",
    }
}
`

Regards,
Bas

**Comment by tcdent** [comment]
Covered in the documentation:

https://github.com/tcdent/php-restclient/blob/master/README.markdown#duplicate-headers-and-parameters
