### ISSUE TITLE
$url as property of the class

### ISSUE THREAD

**Issue by ocjojo** [tcdent/php-restclient#27]
Hi,

I noticed that $url is not a defined property of the RestClient class. However it is used implicitly e.g. [here](https://github.com/tcdent/php-restclient/blob/59a464a76dee3ef7cd390360659c8552f36d054f/restclient.php#L133)
Is there a reason for this? I will gladly create a pull request, if it is not.

The reason I noticed is, that I extend the RestClient class and overwrite the __set and __get functions, which are being called when setting the url. I could also just test for the property name and make an exception in my code. Just curious, why it is not defined explicitly, while all other properties are.

**Comment by tcdent** [comment]
good catch! that should definitely be a property. pull requests welcome!

**Comment by tcdent** [comment]
Thanks for your contribution!
