### ISSUE TITLE
I'm having the same problem when posting messages using Slacks api, it sometimes also return a 100 Continue before the 200 OK.

### ISSUE THREAD

**Issue by vero555** [tcdent/php-restclient#39]
I'm having the same problem when posting messages using Slacks api, it sometimes also return a 100 Continue before the 200 OK.

_Publicación original de @pakomp en https://github.com/tcdent/php-restclient/issues/38#issuecomment-696062149_

**Comment by tcdent** [comment]
Duplicate of #38
