### ISSUE TITLE
PHP 8.2 deprecated "Dollar sign ($) outside of the curly braces"

### ISSUE THREAD

**Issue by DieselPower200** [tcdent/php-restclient#46]
tcdent/php-restclient/restclient.php:268
Using ${var} in strings is deprecated, use {$var} instead

**Comment by magelogger** [comment]
Hi @tcdent! The PR was created https://github.com/tcdent/php-restclient/pull/47

**Comment by tcdent** [comment]
Thank you @magelogger! Merged and released.
