### ISSUE TITLE
Response parsing failed with HTTP code 100

### ISSUE THREAD

**Issue by tungnguyenson** [tcdent/php-restclient#8]
This will break parse_response() function:
http://www.jmarshall.com/easy/http/#http1.1c4

The reason is there's a "\n" between two "HTTP" info

**Comment by Londeren** [comment]
Temporary solution is add `$curlopt[CURLOPT_HTTPHEADER][] = 'Expect:';` to method `execute()`

**Comment by tcdent** [comment]
Thanks for the additional info. I think I ran into this same bug a few years ago with the Twitter API client. 

Trying to fix this without unexpected modifications to the request body; just need to make the header parsing a little more intelligent. Pull requests welcome!

**Comment by tcdent** [comment]
Hey @Londeren, would you mind giving this new version of RestClient a try? I have incorporated support for multiple HTTP status lines in responses. I'll merge it into master after we spend a little more time with it. 

https://github.com/tcdent/php-restclient/tree/multistatus

**Comment by Londeren** [comment]
Hey! I have checked this version. I have some notices like:
> Notice: Undefined index: content_type in [include/vendor/tcdent/php-restclient/restclient.php on line 226](https://github.com/tcdent/php-restclient/blob/multistatus/restclient.php#L226)

But nevertheless this your version of RestClient works fine for my case!

**Comment by tcdent** [comment]
Thanks for the feedback! Just fixed that notice and pushed to the multistatus branch. Hoping for feedback from one more person waiting for this feature, then it'll be in master.

**Comment by tcdent** [comment]
This is resolved in the 0.1.5 release.
